# Generated by Django 2.1.5 on 2019-05-05 20:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facematch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='endtime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='starttime',
            field=models.TimeField(default=datetime.datetime(2019, 5, 5, 20, 44, 43, 331606, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.PositiveIntegerField(),
        ),
    ]
